export const LOGIN_REQUEST = 'LOING_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const RESET_AUTH_ERROR = 'RESET_AUTH_ERROR';

export const UPDATE_WISH_PRODUCT_REQUEST = 'UPDATE_WISH_PRODUCT_REQUEST';
export const UPDATE_WISH_PRODUCT_SUCCESS = 'UPDATE_WISH_PRODUCT_SUCCESS';
export const UPDATE_WISH_PRODUCT_FAIL = 'UPDATE_WISH_PRODUCT_FAIL';

export const DELETE_WISH_PRODUCT_REQUEST = 'DELETE_WISH_PRODUCT_REQUEST';
export const DELETE_WISH_PRODUCT_SUCCESS = 'DELETE_WISH_PRODUCT_SUCCESS';
export const DELETE_WISH_PRODUCT_FAIL = 'DELETE_WISH_PRODUCT_FAIL';
