export const FETCH_TOP_PRODUCTS_REQUEST = 'FETCH_TOP_PRODUCTS_REQUEST';
export const FETCH_TOP_PRODUCTS_SUCCESS = 'FETCH_TOP_PRODUCTS_SUCCESS';
export const FETCH_TOP_PRODUCTS_FAIL = 'FETCH_TOP_PRODUCTS_FAIL';
