export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const RESET_CART_ITEM = 'RESET_CART_ITEM';

export const SAVE_CART_SHIPPING_ADDRESS = 'SAVE_CART_SHIPPING_ADDRESS';
export const SAVE_CART_PAYMENT_METHOD = 'SAVE_CART_PAYMENT_METHOD';

export const USER_UPDATE_DETAILS_SUCCESS = 'USER_UPDATE_DETAILS_SUCCESS';
export const USER_UPDATE_DETAILS_FAIL = 'USER_UPDATE_DETAILS_FAIL';
export const USER_UPDATE_DETAILS_RESET = 'USER_UPDATE_DETAILS_RESET';

export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';
