export const FETCH_LATEST_PRODUCTS_REQUEST = 'FETCH_LATEST_PRODUCTS_REQUEST';
export const FETCH_LATEST_PRODUCTS_SUCCESS = 'FETCH_LATEST_PRODUCTS_SUCCESS';
export const FETCH_LATEST_PRODUCTS_FAIL = 'FETCH_LATEST_PRODUCTS_FAIL';
export const FETCH_LATEST_PRODUCTS_CANCELLED =
  'FETCH_LATEST_PRODUCTS_CANCELLED';
