export const FETCH_MY_ORDERS_REQUEST = 'FETCH_MY_ORDERS_REQUEST';
export const FETCH_MY_ORDERS_SUCCESS = 'FETCH_MY_ORDERS_SUCCESS';
export const FETCH_MY_ORDERS_FAIL = 'FETCH_MY_ORDERS_FAIL';

export const RESET_MY_ORDERS = 'RESET_MY_ORDERS';
