export const FETCH_MY_ORDERS_SUCCESS = 'FETCH_MY_ORDERS_SUCCESS';
export const FETCH_MY_ORDERS_FAIL = 'FETCH_MY_ORDERS_FAIL';
export const RESET_MY_ORDERS_DETAILS = 'RESET_MY_ORDERS_DETAILS';

export const FETCH_MY_ORDER_REQUEST = 'FETCH_MY_ORDER_REQUEST';
export const FETCH_MY_ORDER_SUCCESS = 'FETCH_MY_ORDER_SUCCESS';
export const FETCH_MY_ORDER_FAIL = 'FETCH_MY_ORDER_FAIL';

export const UPDATE_ORDER_PAY_REQUEST = 'UPDATE_ORDER_PAY_REQUEST';
export const UPDATE_ORDER_PAY_SUCCESS = 'UPDATE_ORDER_PAY_SUCCESS';
export const UPDATE_ORDER_PAY_FAIL = 'UPDATE_ORDER_PAY_FAIL';

export const RESET_MY_ORDER = 'RESET_MY_ORDER';
