export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const UPDATE_ORDER_PAY_SUCCESS = 'UPDATE_ORDER_PAY_SUCCESS';
export const UPDATE_ORDER_PAY_FAIL = 'UPDATE_ORDER_PAY_FAIL';

export const UPDATE_ORDER_DELIVER_SUCCESS = 'UPDATE_ORDER_DELIVER_SUCCESS';
export const UPDATE_ORDER_DELIVER_FAIL = 'UPDATE_ORDER_DELIVER_FAIL';
