export const FETCH_MY_ORDERS_SUCCESS = 'FETCH_MY_ORDERS_SUCCESS';
export const FETCH_MY_ORDERS_FAIL = 'FETCH_MY_ORDERS_FAIL';
export const RESET_MY_ORDERS_DETAILS = 'RESET_MY_ORDERS_DETAILS';

export const FETCH_MY_ORDER_SUCCESS = 'FETCH_MY_ORDER_SUCCESS';
export const FETCH_MY_ORDER_FAIL = 'FETCH_MY_ORDER_FAIL';
