export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
export const FETCH_ORDERS_CANCELLED = 'FETCH_ORDERS_CANCELLED';

export const FETCH_MY_ORDERS_REQUEST = 'FETCH_MY_ORDERS_REQUEST';
export const FETCH_MY_ORDERS_SUCCESS = 'FETCH_MY_ORDERS_SUCCESS';
export const FETCH_MY_ORDERS_FAIL = 'FETCH_MY_ORDERS_FAIL';
export const FETCH_MY_ORDERS_CANCELLED = 'FETCH_MY_ORDERS_CANCELLED';
