export const FETCH_MY_ORDER_REQUEST = 'FETCH_MY_ORDER_REQUEST';
export const FETCH_MY_ORDER_SUCCESS = 'FETCH_MY_ORDER_SUCCESS';
export const FETCH_MY_ORDER_FAIL = 'FETCH_MY_ORDER_FAIL';
export const FETCH_MY_ORDER_CANCELLED = 'FETCH_MY_ORDER_CANCELLED';

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';

export const UPDATE_ORDER_PAY_REQUEST = 'UPDATE_ORDER_PAY_REQUEST';
export const UPDATE_ORDER_PAY_SUCCESS = 'UPDATE_ORDER_PAY_SUCCESS';
export const UPDATE_ORDER_PAY_FAIL = 'UPDATE_ORDER_PAY_FAIL';

export const UPDATE_ORDER_DELIVER_REQUEST = 'UPDATE_ORDER_DELIVER_REQUEST';
export const UPDATE_ORDER_DELIVER_SUCCESS = 'UPDATE_ORDER_DELIVER_SUCCESS';
export const UPDATE_ORDER_DELIVER_FAIL = 'UPDATE_ORDER_DELIVER_FAIL';

export const RESET_ORDER = 'RESET_ORDER';
