export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const UPDATE_ORDER_DELIVER_REQUEST = 'UPDATE_ORDER_DELIVER_REQUEST';
export const UPDATE_ORDER_DELIVER_SUCCESS = 'UPDATE_ORDER_DELIVER_SUCCESS';
export const UPDATE_ORDER_DELIVER_FAIL = 'UPDATE_ORDER_DELIVER_FAIL';
